//{{NO_DEPENDENCIES}}
// Fichier Include généré de Microsoft Visual C++.
// Utilisé par OpenOpcUaQuickClient.rc
//
#define IDD_UAQUICKCLIENT_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDD_UA_BROWSER_DIALOG           129
#define IDR_TREECTRL_SESSION_CONTEXT_MENU 130
#define IDR_TREECTRL_SUBSCRIPTION_CONTEXT_MENU 131
#define IDR_BROWSE_MENU                 132
#define IDD_BROWSE_OPTION_DIALOG        133
#define IDD_EXPORT_DIALOG               134
#define IDD_SESSION_PARAMS_DIALOG       136
#define IDD_SUBSCRIPTION_PARAM_DLG      137
#define IDI_ICON_OPEN_OPC_UA            139
#define IDR_MONITORED_ITEM_CONTEXT_MENU 140
#define IDD_ATTRIBUTES_DIALOG           141
#define IDD_DIALOG_ENDPOINT_URL         142
#define IDI_REFRESH                     144
#define IDI_CONNECT                     146
#define IDI_DISCONNECT                  147
#define IDI_SUBSCRIPTION_ACTIVE         148
#define IDI_SUBSCRIPTION_INACTIVE       149
#define IDI_SESSION_ACTIVE              150
#define IDI_ICON1                       151
#define IDI_SESSION_INACTIVE            151
#define IDD_MESSAGE_DLG                 152
#define IDR_MAIN_MENU                   153
#define IDD_DISCOVERY_DIALOG            154
#define IDI_ICON2                       157
#define IDI_GREEN_CHECK                 157
#define IDI_GREEN_REFRESH               159
#define IDI_DATATYPE_STRING             160
#define IDI_BROWSE                      161
#define IDI_ATTRIBUTES                  162
#define IDI_MESSAGE                     163
#define IDI_EXIT                        165
#define IDD_MONITOREDITEM_DIALOG        166
#define IDD_WRITE                       216
#define IDD_WRITE_DIALOG                216
#define IDC_TAG_NAME                    234
#define IDC_NODEID                      234
#define IDC_TAG_VAL_STR                 235
#define IDC_ATTRIBUTE_VAL_STR           235
#define IDC_TAG_VAL                     236
#define IDC_ATTRIBUTE_VAL               236
#define IDC_SPIN_REQUESTEDVALUE         237
#define IDC_LIST_ARRAY                  238
#define IDC_TREE1                       1000
#define IDC_TREE_SESSION_SUBSCRIPTION   1000
#define IDC_EDIT_HOST                   1002
#define IDC_COMBO_APP_NAME              1003
#define IDC_BUTTON_CONNECT              1007
#define IDC_MONITORED_ITEMCTRL          1008
#define IDC_COMBO_ENDPOINT_DESCRIPTION  1009
#define IDC_COMBO1                      1010
#define IDC_COMBO_BROWSE_DIRECTION      1010
#define IDC_COMBO_ATTRIBUTEID           1010
#define IDC_COMBO_TIMESTAMP_TO_RETURN   1010
#define IDC_SELECT_FILE_BUTTON          1011
#define IDC_COMBO_DEADBAND_TYPE         1011
#define IDC_EDIT_FILENAME               1012
#define IDC_CHECK1                      1013
#define IDC_KEEPALIVE_EDIT              1014
#define IDC_MAX_MESSAGESIZE_EDIT        1015
#define IDC_CHECK2                      1018
#define IDC_CHECK3                      1019
#define IDC_CHECK4                      1020
#define IDC_EXPORT_BUTTON               1021
#define IDC_EXPORT_RESULT               1022
#define IDC_PRIORITY                    1023
#define IDC_PUBLISHING_INTERVAL         1024
#define IDC_LIFETIME_COUNT              1025
#define IDC_KEEPALIVE_COUNT             1026
#define IDC_MAX_NOTIFICATION_PER_PUBLISH 1027
#define IDC_CHECK_PUBLISHING_ENABLED    1028
#define IDC_COMBO_DATATYPE              1029
#define IDC_EDIT_ENDPOINTURL            1031
#define IDC_BUTTON_REFRESH_ATTRIBUTES   1032
#define IDC_MESSAGE_LIST                1034
#define IDC_EDIT_HOSTNAME               1035
#define IDC_RADIO_NONE                  1042
#define IDC_RADIO_SIGN                  1043
#define IDC_RADIO_SIGN_ENCRYPT          1044
#define IDC_EDIT_SECURITY_POLICY_URI    1045
#define IDC_SPIN_ENDPOINT_DESCRIPTION   1046
#define IDC_EDITENDPOINT_DESCRIPTION    1047
#define IDC_CURRENT_ENDPOINT_DESCRIPTION 1049
#define IDC_NODEIDS_TREE                1050
#define IDC_EDIT_BROWSENAME             1051
#define IDC_SELECT_BUTTOM               1051
#define IDC_NODE_ATTRIBUTES_LIST        1052
#define IDC_REFRESH_BUTTON              1052
#define IDC_BUTTON_SUBSCRIBE            1053
#define IDC_BUTTON_BROWSE               1053
#define IDC_BUTTON_MONITOR_ITEM         1054
#define IDC_BUTTON_ATTRIBUTE            1054
#define IDC_EDIT_QUEUE_SIZE             1054
#define IDC_TREE_SUBSCRIPTION           1055
#define IDC_BUTTON_MESSAGE              1055
#define IDC_EDIT_SAMPLING_INTERVAL      1055
#define IDC_LIST_ITEM_LIST              1056
#define IDC_BUTTON_EXIT                 1056
#define IDC_EDIT_DEADBAND_VALUE         1056
#define IDC_CHECK_UNSPECIFIED_NODECLASS 1057
#define IDC_CHECK_METHOD_NODECLASS      1058
#define IDC_CHECK_DISCARD_OLDEST        1058
#define IDC_CHECK_REFERENCETYPE_NODECLASS 1059
#define IDC_CHECK_VALUE                 1059
#define IDC_CHECK_OBJECT_NODECLASS      1060
#define IDC_CHECK_STATUSCODE            1060
#define IDC_CHECK_OBJECTTYPE_NODECLASS  1061
#define IDC_CHECK_TIMESTAMP             1061
#define IDC_CHECK_DATATYPE_NODECLASS    1062
#define IDC_CHECK_VARIABLE_NODECLASS    1063
#define IDC_CHECK_VARIABLETYPE_NODECLASS 1064
#define IDC_CHECK_VIEW                  1065
#define IDC_CHECK_VIEW_NODECLASS        1066
#define IDI_DATATYPE                    2000
#define IDI_DATA_TYPE                   2001
#define IDI_FINDSERVERS                 2002
#define IDI_METHOD                      2003
#define IDI_OBJECT                      2004
#define IDI_OBJECT_TYPE                 2005
#define IDI_REFERENCE_TYPE              2006
#define IDI_UNSPECIFIED                 2007
#define IDI_VARIABLE                    2008
#define IDI_VARIABLE_TYPE               2009
#define IDI_VIEW                        2010
#define IDI_OPC                         2011
#define IDI_DATATYPE_LOGIC              2012
#define IDI_DATATYPE_NUMERIC            2013
#define ID__CLOSESESSION                32771
#define ID__BROWSE                      32772
#define ID__CREATESUBSCRIPTION          32773
#define IDM_CLOSE_SESSION               32774
#define IDM_BROWSE                      32775
#define IDM_CREATE_SUBSCRIPTION         32776
#define ID__MONITOREDMODE               32777
#define ID__ADDMONITOREDITEMS           32778
#define ID__REMOVESUBSCRIPTION          32779
#define ID__CHANGEPARAMS                32780
#define ID__BROWSEOPTION                32781
#define ID__EXPORT                      32782
#define IDM_EXPORT                      32783
#define IDM_BROWSE_OPTION               32784
#define ID__MONITOR                     32785
#define IDM_MONITOR                     32786
#define IDM_ADD_MONITOREDITEMS          32787
#define ID__ATTRIBUTES                  32788
#define ID__WRITE                       32789
#define ID__DELETE                      32790
#define IDM_ATTRIBUTES                  32791
#define IDM_WRITE                       32792
#define IDM__DELETE                     32793
#define IDM_DELETE                      32794
#define IDM_WRITE_ATTRIBUTES            32795
#define IDM_READ_ATTRIBUTES             32796
#define ID_FILE_LOAD                    32800
#define ID_FILE_SAVE32801               32801
#define ID_FILE_EXIT                    32802
#define ID_VIEW_MESSAGE                 32803
#define ID_VIEW_ATTRIBUTE               32804
#define ID_DISCOVER_SERVER              32805
#define IDM_DISCOVER_SERVER             32806
#define ID_VIEW_BROWSER                 32807
#define ID__MODIFY                      32808
#define IDM_MODIFY                      32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
